export const Routes = {
  AUTH_NAVIGATOR: 'AUTH_NAVIGATOR',
  WELCOME: 'WELCOME',
  SIGN_IN: 'SIGN_IN',

  SIGN_UP_MAIN: 'SIGN_UP_MAIN',
  SIGN_UP_COMPANY: 'SIGN_UP_COMPANY',
  SIGN_UP_PARTICIPANT: 'SIGN_UP_PARTICIPANT',

  BOTTOM_TAB_BAR_NAVIGATOR: 'BOTTOM_TAB_BAR_NAVIGATOR',

  MAIN_NAVIGATOR: 'MAIN_NAVIGATOR',
  HOME: 'HOME',

  SETTINGS_NAVIGATOR: 'SETTINGS_NAVIGATOR',
  SETTINGS: 'SETTINGS',

  NOTIFICATIONS_NAVIGATOR: 'NOTIFICATIONS_NAVIGATOR',
  NOTIFICATIONS: 'NOTIFICATIONS',

  MY_TASKS_NAVIGATOR: 'MY_TASKS_NAVIGATOR',
  MY_TASKS: 'MY_TASKS',

  AUTH: 'AUTH',
} as const;
